[platformio]
default_envs = lilygo-t3-433
src_dir = codex_radiogate/src

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -DCORE_DEBUG_LEVEL=3
    -DASYNCWEBSERVER_REGEX
lib_deps =
    jgromes/RadioLib @ 6.6.0
    ottowinter/ESPAsyncWebServer-esphome @ ^3.1.0
    bblanchon/ArduinoJson @ ^7.0.4

[env:lilygo-t3-433]
build_flags =
    ${env.build_flags}
    -DRADIO_PROFILE_DEFAULT=433920000UL

[env:lilygo-t3-470]
build_flags =
    ${env.build_flags}
    -DRADIO_PROFILE_DEFAULT=470000000UL
